tpd:
  peer1Port: 8761
  peer2Port: 8762
  peer3Port: 8763

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: '*'
eureka:
  client:
    service-url:
      defaultZone: http://eureka-peer1:${tpd.peer1Port}/eurekak,http://eureka-peer2:${tpd.peer2Port}/eureka,http://eureka-peer3:${tpd.peer3Port}/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

---
spring:
  profiles: peer1
eureka:
  instance:
    hostname: eureka-peer1
    appname: eureka-cluster
server:
  port: ${tpd.peer1Port}

---
spring:
  profiles: peer2
eureka:
  instance:
    hostname: eureka-peer2
    appname: eureka-cluster
server:
  port: ${tpd.peer2Port}

---
spring:
  profiles: peer3
eureka:
  instance:
    hostname: eureka-peer3
    appname: eureka-cluster
server:
  port: ${tpd.peer3Port}